# Generated by Django 5.2.5 on 2026-03-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=255)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
